version: '3.5'

services:
  service1:
    image: alinz/baker.go:latest

    environment:
      - ACME=false
      - ACME_PATH=/acme/cert

    ports:
      - '80:80'
      - '443:443'

    networks:
      - baker

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme/cert:/acme/cert

networks:
  baker:
    name: baker_net
    driver: bridge
