version: '3.5'

services:
  service1:
    image: baker/service:latest

    labels:
      - 'baker.network=baker_net'
      - 'baker.service.port=8000'
      - 'baker.service.ping=/config'

    networks:
      - baker

networks:
  baker:
    external:
      name: baker_net    